### Vectors (Rank 1 Tensors) in NumPy

In [185]:
import numpy as np

In [186]:
# Membuat vector x dengan ukuran 3x1
x = np.array([[26],[7],[11]]) # type argument is optional, e.g.: dtype=np.float16
x

array([[26],
       [ 7],
       [11]])

In [187]:
# Hitung panjang vector x
len(x)

3

In [188]:
# Tampilkan ukuran vector x
x.shape

(3, 1)

In [189]:
# Tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [190]:
# Akses elemen pertama dari vector x
x[0] # zero-indexed

array([26])

In [191]:
# Tampilkan tipe data elemen pertama dari vector x
type(x[0,0])

numpy.int64

*Vector Transposition*

In [192]:
# Lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t


array([[26,  7, 11]])

In [193]:
# Tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [194]:
# Diasumsikan ada vector y
y = np.array([[26],[7],[11]])
y

array([[26],
       [ 7],
       [11]])

In [195]:
# tampilkan ukuran vektor y
y.shape

(3, 1)

In [196]:
# Lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t

array([[26,  7, 11]])

In [197]:
# Tampilkan ukuran dari vector y_t (koreksi soal: menampilkan y_t)
y_t.shape # this is a column vector as it has 3 rows and 1 column

(1, 3)

In [198]:
# Column vector can be transposed back to original row vector:
y_t.T

array([[26],
       [ 7],
       [11]])

In [199]:
y_t.T.shape

(3, 1)

### Vectors in PyTorch and TensorFlow

In [200]:
import torch
import tensorflow as tf


In [201]:
x_pt = torch.tensor([[26],[7],[11]])
x_pt

tensor([[26],
        [ 7],
        [11]])

In [202]:
x_tf = tf.Variable([[26],[7], [11]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[26],
       [ 7],
       [11]], dtype=int32)>