### Tensor Transposition

# 1

menggunakan numpy

In [52]:
import numpy as np

In [53]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[9, 7, 26], [4, 8, 6]])
X

array([[ 9,  7, 26],
       [ 4,  8,  6]])

menggunakan Pytorch

In [54]:
import torch

In [55]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[10, 47, 26], [0, 18, 86]])
X_pt

tensor([[10, 47, 26],
        [ 0, 18, 86]])

menggunakan TensorFlow

In [56]:
import tensorflow as tf

In [57]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[11, 97, 46], [10, 68, 8]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[11, 97, 46],
       [10, 68,  8]], dtype=int32)>

# 2

In [58]:
# lakukan transpose pada matrix X (Numpy)
X.T

array([[ 9,  4],
       [ 7,  8],
       [26,  6]])

In [59]:
# lakukan transpose pada matrix X_pt (Pytorch)
X_pt.T

tensor([[10,  0],
        [47, 18],
        [26, 86]])

In [60]:
# lakukan transpose pada matrix X_tf (TensorFlow)
tf.transpose(X_tf) # less Pythonic

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 10],
       [97, 68],
       [46,  8]], dtype=int32)>