soal no 1

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [4]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[20, 3, 7], [17, 6, 7]])
X

array([[20,  3,  7],
       [17,  6,  7]])

In [5]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[20, 3, 7], [17, 6, 7]])
X_pt

tensor([[20,  3,  7],
        [17,  6,  7]])

In [7]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflo
X_tf = tf.Variable([[20, 3, 7], [17, 6, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[20,  3,  7],
       [17,  6,  7]], dtype=int32)>

In [13]:
# lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar
scalar = 3

X_scaled = X * scalar
X_pt_scaled = X_pt * scalar
X_tf_scaled = X_tf * scalar

print("Scaled NumPy matrix (X):")
print(X_scaled)

print("\nScaled PyTorch tensor (X_pt):")
print(X_pt_scaled)

print("\nScaled TensorFlow variable (X_tf):")
print(X_tf_scaled)

Scaled NumPy matrix (X):
[[60  9 21]
 [51 18 21]]

Scaled PyTorch tensor (X_pt):
tensor([[60,  9, 21],
        [51, 18, 21]])

Scaled TensorFlow variable (X_tf):
tf.Tensor(
[[60  9 21]
 [51 18 21]], shape=(2, 3), dtype=int32)


In [14]:
# lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar
scalar = 3

X_scaled = X + scalar
X_pt_scaled = X_pt + scalar
X_tf_scaled = X_tf + scalar

print("Scaled NumPy matrix (X):")
print(X_scaled)

print("\nScaled PyTorch tensor (X_pt):")
print(X_pt_scaled)

print("\nScaled TensorFlow variable (X_tf):")
print(X_tf_scaled)

Scaled NumPy matrix (X):
[[23  6 10]
 [20  9 10]]

Scaled PyTorch tensor (X_pt):
tensor([[23,  6, 10],
        [20,  9, 10]])

Scaled TensorFlow variable (X_tf):
tf.Tensor(
[[23  6 10]
 [20  9 10]], shape=(2, 3), dtype=int32)


In [15]:
# lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar
scalar = 3

X_scaled = X - scalar
X_pt_scaled = X_pt - scalar
X_tf_scaled = X_tf - scalar

print("Scaled NumPy matrix (X):")
print(X_scaled)

print("\nScaled PyTorch tensor (X_pt):")
print(X_pt_scaled)

print("\nScaled TensorFlow variable (X_tf):")
print(X_tf_scaled)

Scaled NumPy matrix (X):
[[17  0  4]
 [14  3  4]]

Scaled PyTorch tensor (X_pt):
tensor([[17,  0,  4],
        [14,  3,  4]])

Scaled TensorFlow variable (X_tf):
tf.Tensor(
[[17  0  4]
 [14  3  4]], shape=(2, 3), dtype=int32)


soal no 2

In [17]:
# buat matrix Y dengan ukuran 2x3 menggunakan numpy
Y = np.array([[7, 3, 20], [7, 6, 17]])
Y

array([[ 7,  3, 20],
       [ 7,  6, 17]])

In [18]:
# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = torch.tensor([[7, 3, 20], [7, 6, 17]])
Y_pt

tensor([[ 7,  3, 20],
        [ 7,  6, 17]])

In [19]:
# buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
Y_tf = tf.Variable([[7, 3, 20], [7, 6, 17]])
Y_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 7,  3, 20],
       [ 7,  6, 17]], dtype=int32)>

In [20]:
# kalikan matrix X dengan Y
X * Y

array([[140,   9, 140],
       [119,  36, 119]])

In [21]:
# kalikan matrix X_pt dengan Y_pt
X_pt * Y_pt

tensor([[140,   9, 140],
        [119,  36, 119]])

In [22]:
# kalikan matrix X_tf dengan Y_tf
X_tf * Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[140,   9, 140],
       [119,  36, 119]], dtype=int32)>