soal no 1

In [4]:
import numpy as np
import torch
import tensorflow as tf

In [5]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[20, 3, 7], [17, 6, 7]])
X

array([[20,  3,  7],
       [17,  6,  7]])

In [6]:
# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
X.sum()

np.int64(60)

In [10]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[20, 3, 7], [17, 6, 7]])
X_pt

tensor([[20,  3,  7],
        [17,  6,  7]])

In [9]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[20, 3, 7], [17, 6, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[20,  3,  7],
       [17,  6,  7]], dtype=int32)>

soal no 2

In [11]:
# hitung hasil penjumlahan seluruh elemen matrix X
X.sum()

np.int64(60)

In [12]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt
torch.sum(X_pt)

tensor(60)

In [13]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=60>

soal no 3

In [14]:
# hitung hasil penjumlahan matrix X berdasarkan row nya
X.sum(axis=1)

array([30, 30])

In [17]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya
torch.sum(X_pt, axis=1)

tensor([30, 30])

In [18]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya
tf.reduce_sum(X_tf, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([30, 30], dtype=int32)>

soal no 4

In [19]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya
X.sum(axis=0)

array([37,  9, 14])

In [20]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
torch.sum(X_pt, axis=0)

tensor([37,  9, 14])

In [21]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
tf.reduce_sum(X_tf, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([30, 30], dtype=int32)>

soal no 5

In [38]:
# hitung nilai minimal dari matrix X
X.min()

np.int64(3)

In [39]:
# hitung nilai minimal dari matrix X_pt
X_pt.min()

tensor(3)

In [40]:
# hitung nilai minimal dari matrix X_tf
tf.reduce_min(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [41]:
# hitung nilai maksimal dari matrix X
X.max()

np.int64(20)

In [42]:
# hitung nilai maksimal dari matrix X_pt
X_pt.max()

tensor(20)

In [43]:
# hitung nilai maksimal dari matrix X_tf
tf.reduce_max(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [44]:
# hitung nilai rata-rata dari matrix X
X.mean()

np.float64(10.0)

In [46]:
# hitung nilai rata-rata dari matrix X_pt
X_pt.float().mean()

tensor(10.)

In [47]:
# hitung nilai rata-rata dari matrix X_tf
tf.reduce_mean(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

soal no 6

In [48]:
# hitung hasil perkalian seluruh elemen matrix X
X.prod()

np.int64(299880)

In [49]:
# hitung hasil perkalian seluruh elemen matrix X_pt
X_pt.prod()

tensor(299880)

In [50]:
# hitung hasil perkalian seluruh elemen matrix X_tf
tf.reduce_prod(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=299880>