$No.1$

In [ ]:
import numpy as np

In [ ]:
x = np.array([19, 4, 7])
print(x)

[19  4  7]


In [ ]:
y = np.array([0, 2, 4])
print(y)

[0 2 4]


In [ ]:
import torch

In [ ]:
# buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch
x_pt = torch.tensor([19, 4, 7])
print(x_pt)

tensor([19,  4,  7])


In [ ]:
y_pt = torch.tensor([0, 2, 4])
print(y_pt)

tensor([0, 2, 4])


In [ ]:
import tensorflow as tf

In [ ]:
# buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow
x_tf = tf.Variable([19, 4, 7])
print(x_tf)


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([19,  4,  7], dtype=int32)>


$No.2$

In [ ]:
y_tf = tf.Variable([0, 2, 4])
print(y_tf)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 2, 4], dtype=int32)>


In [ ]:
# hitung perkalian dot product antara vector x dan vector y
np.dot(x, y)

np.int64(36)

In [ ]:
# hitung perkalian dot product antara vector x_pt dan vector y_pt
torch.dot(x_pt, y_pt)

tensor(36)

In [ ]:
# hitung perkalian dot product antara vector x_tf dan vector y_tf
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=36>

$No.3$

In [77]:
# What is Y_Transpose?
Y = np.array([[42, 4, 7, 99],
              [-99, -3, 17, 22]])
Y_transpose

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

In [78]:
# What is The Hadamard product of these matrices?
A = np.array([[25, 10],
              [-2, 1]])

B = np.array([[-1, 7],
              [10, 8]])
A*B

array([[-25,  70],
       [-20,   8]])

In [79]:
# What is the product of the tensor w and x?
w = np.array([-1, 2, -2])
x = np.array([5, 10, 0])
np.dot(w, x)

np.int64(15)