# **Frobenius Norm**

1. menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm

menggunakan numpy

In [111]:
import numpy as np

In [112]:
# Membuat matriks 3x3
X = np.array([[26, 7, 11], [10, 4, 9],[6, 3, 1]])
X

array([[26,  7, 11],
       [10,  4,  9],
       [ 6,  3,  1]])

In [113]:
# Menghitung Frobenius Norm secara manual
(26**2 + 7**2 + 11**2 + 10**2 + 4**2 + 9**2 + 6**2 + 3**2 + 1**2)**(1/2)

33.0

In [114]:
# Menghitung Frobenius Norm
np.linalg.norm(X)

np.float64(33.0)

menggunakan pytorch

In [115]:
import torch

In [116]:
#  Membuat matriks 3x3
X_pt = torch.tensor([[26, 7, 11], [10, 4, 9],[6, 3, 1]]) # torch.norm() supports floats only
X_pt

tensor([[26,  7, 11],
        [10,  4,  9],
        [ 6,  3,  1]])

In [117]:
# hitung nilai frobenius norm menggunakan Pytorch
np.linalg.norm(X) # same function as for vector L2 norm

np.float64(33.0)

menggunakan tensorflow

In [118]:
import tensorflow as tf

In [119]:
# Membuat matriks 3x3
X_tf = tf.Variable([[26, 7, 11], [10, 4, 9],[6, 3, 1]], dtype=tf.float32) # tf.norm() also supports floats only
X_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[26.,  7., 11.],
       [10.,  4.,  9.],
       [ 6.,  3.,  1.]], dtype=float32)>

In [120]:
# hitung nilai frobenius norm menggunakan TensorFlow

tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=33.0>