## Matrix Multiplication (with a Vector)

1

menggunakan numpy

In [469]:
import numpy as np

In [470]:
# buat matrix A dengan ukuran 2x3 menggunakan numpy
A = np.array([[16, 1, 7], [5, 6, 9]])
A

array([[16,  1,  7],
       [ 5,  6,  9]])

In [471]:
# vector b berukuran 3x1 menggunakan numpy
b = np.array([[5], [7], [3]])
b

array([[5],
       [7],
       [3]])

menggunakan pytorch

In [472]:
import torch

In [473]:
# buat matrix A_pt dengan ukuran 2x3 menggunakan pytorch
A_pt = torch.tensor([[16, 1, 7], [5, 6, 9]])
A_pt

tensor([[16,  1,  7],
        [ 5,  6,  9]])

In [474]:
# vector b_pt berukuran 3x1 menggunakan pytorch
b_pt = torch.tensor([[5], [7], [3]])
b_pt

tensor([[5],
        [7],
        [3]])

menggunakan tensorflow

In [475]:
import tensorflow as tf

In [476]:
# buat matrix A_tf dengan ukuran 2x3 menggunakan tensorflow
A_tf = tf.Variable([[16, 1, 7], [5, 6, 9]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[16,  1,  7],
       [ 5,  6,  9]], dtype=int32)>

In [477]:
# vector b_tf berukuran 3x1 menggunakan tensorflow
b_tf = tf.Variable([[5], [7], [3]])
b_tf

# digunakannya tf.Variable digunakan jika nilai tersebut perlu diperbarui, seperti pada proses training model.

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[5],
       [7],
       [3]], dtype=int32)>

2. tampilkan ukuran matrix A dan vector b

In [478]:
# numpy
print("NumPy A shape:", A.shape)
print("NumPy b shape:", b.shape)

# pytorch
print("PyTorch A_pt shape:", A_pt.shape)
print("PyTorch b_pt shape:", b_pt.shape)

# TensorFlow
print("TensorFlow A_tf shape:", A_tf.shape)
print("TensorFlow b_tf shape:", b_tf.shape)

NumPy A shape: (2, 3)
NumPy b shape: (3, 1)
PyTorch A_pt shape: torch.Size([2, 3])
PyTorch b_pt shape: torch.Size([3, 1])
TensorFlow A_tf shape: (2, 3)
TensorFlow b_tf shape: (3, 1)


3

In [479]:
# kalikan matrix A dengan vector b
np.dot(A, b)

array([[108],
       [ 94]])

In [480]:
# kalikan matrix A dengan vector b
torch.matmul(A_pt, b_pt)

tensor([[108],
        [ 94]])

In [481]:
# kalikan matrix A dengan vector b
tf.linalg.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[108],
       [ 94]], dtype=int32)>

4



In [482]:
# buat matrix B dengan ukuran 3x3 menggunakan NUMPY
B = np.array([[8, 10, 2],[9, 1, 3],[4, 0, 6]])
B

array([[ 8, 10,  2],
       [ 9,  1,  3],
       [ 4,  0,  6]])

In [483]:
# buat matrix B_pt dengan ukuran 3x3 menggunakan Pytorch
B_pt = torch.tensor([[8, 10, 2],[9, 1, 3],[4, 0, 6]])
B_pt

tensor([[ 8, 10,  2],
        [ 9,  1,  3],
        [ 4,  0,  6]])

In [484]:
# buat matrix B_tf dengan ukuran 3x3 menggunakan Tensorflow
B_tf = tf.constant([[8, 10, 2],[9, 1, 3],[4, 0, 6]])
B_tf

# Digunakan tf.constant karena nilai matriks/vektor bersifat tetap dan tidak mengalami perubahan selama program berjalan.

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 8, 10,  2],
       [ 9,  1,  3],
       [ 4,  0,  6]], dtype=int32)>

5

In [485]:
# kalikan matrix A dengan matrix B (Numpy)
AB_np = np.dot(A, B)
AB_np

array([[165, 161,  77],
       [130,  56,  82]])

In [486]:
# kalikan matrix A_pt dengan matrix B_pt (Pytorch)
AB_pt = torch.matmul(A_pt, B_pt)
AB_pt

tensor([[165, 161,  77],
        [130,  56,  82]])

In [487]:
# kalikan matrix A_tf dengan matrix B_tf
AB_tf = tf.matmul(A_tf, B_tf)
AB_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[165, 161,  77],
       [130,  56,  82]], dtype=int32)>

6. buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

In [488]:
# NUMPY
BA_np = np.dot(B, A)   # ini akan ERROR

# karena (3x3) x (2x3)
# syarat perkalian matrix:
# jumlah kolom matrix pertama harus = jumlah baris matrix kedua
# di sini:
# kolom B = 3
# baris A = 2
# 3 ≠ 2 -> tidak memenuhi syarat -> maka akan terjadi ERROR

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
# PYTORCH
BA_pt = torch.matmul(B_pt, A_pt)  # ERROR

# (3x3) x (2x3)
# kolom B (3) ≠ baris A (2)
# sehingga tidak bisa dikalikan

In [ ]:
# TENSORFLOW
BA_tf = tf.matmul(B_tf, A_tf)  # ERROR

# (3x3) x (2x3)
# kolom pertama (3) tidak sama dengan baris kedua (2)
# maka operasi tidak valid

**Kesimpulan**: Karena $BA$ bahkan tidak bisa dihitung dalam kasus ini, maka jelas $AB \neq BA$. Sekalipun kedua matriks berbentuk persegi (misal $3 \times 3$), hasil elemen di dalamnya biasanya akan berbeda. Jadi, perkalian matriks **tidak komutatif.**