In [1]:
import numpy as np

In [3]:
#buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
X_sym = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [4]:
#membuktikan bahwa matriks tersebut simetris dengan cara transpose, karena jika simetris X=X transpose
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [6]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
#menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4
import torch

In [22]:
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [23]:
#menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
b_pt = torch.tensor([ 1, 2, 3, 4])
b_pt

tensor([1, 2, 3, 4])

In [24]:
#kalikan matrix I dengan vector b_pt
torch.matmul(I, b_pt)

tensor([1, 2, 3, 4])