In [3]:
#lakukan perhitungan soal excercise menggunakan collab
import torch

In [4]:
x = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [15]:
b = torch.tensor([[-1, 1, -2], [0, 1, 2]]).T
b

tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])

In [16]:
torch.matmul(x,b)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])