In [2]:
#buat matrix X ukuran 2x2 menggunakan numpy
import numpy as np
x = np.array([[1, 2], [3, 4]])
x


array([[1, 2],
       [3, 4]])

In [4]:
#buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(x)
Xinv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
#kalikan X dengan Xinv menggunakan numpy
p = np.matmul(x, Xinv)
p

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [11]:
#selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch
import numpy as np

A = np.array([[4, 2], [-5, -3]])
B = np.array([4, -7])

x = np.linalg.solve(A, B)
x #hasil dari x merupakan nilai b dan c, dimana b adalah indeks pertama dan c adalah indeks kedua, sesuai dengan urutan di soal yaitu b pertama dan c kedua

array([-1.,  4.])

In [15]:
import torch

A_pt = torch.tensor([[4.0, 2.0], [-5.0, -3.0]])
B_pt = torch.tensor([4.0, -7.0])

x_pt = torch.linalg.solve(A_pt, B_pt)
x_pt # sama seperti NumPy tadi

tensor([-1.,  4.])

In [19]:
import tensorflow as tf

A_tf = tf.constant([[4.0, 2.0], [-5.0, -3.0]])
B_tf = tf.constant([[4.0], [-7.0]])

x_tf = tf.linalg.solve(A_tf, B_tf)
x_tf # sama seperti NumPy dan torch tadi untuk indeksnya

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.99999946],
       [ 3.999999  ]], dtype=float32)>