**Matrics**

In [97]:
import numpy as np

In [98]:
# Membuat matrix X berukuran 2x3

X = np.array([[26, 7, 11], [20, 9, 16]])
X

array([[26,  7, 11],
       [20,  9, 16]])

In [99]:
# Tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [100]:
X.size

6

In [101]:
# Tampilkan seluruh elemen dari kolom pertama

X[:,0]

array([26, 20])

In [102]:
# Tampilkan seluruh elemen dari baris kedua

X[1,:]

array([20,  9, 16])

### Matrices in **PyTorch**

In [103]:
import torch

In [104]:
# Membuat matrix X berukuran 2x3

X_pt = torch.tensor([[26, 7, 11], [20, 9, 16]])
X_pt

tensor([[26,  7, 11],
        [20,  9, 16]])

In [105]:
# Tampilkan ukuran dari matrix X

X_pt.shape

torch.Size([2, 3])

In [106]:
# Tampilkan seluruh elemen dari kolom pertama

X_pt[1,:]

tensor([20,  9, 16])

**Matrices in TensorFlow**

In [107]:
import tensorflow as tf

In [108]:
# Membuat matrix X berukuran 2x3

X_tf = tf.Variable([[26, 7, 11], [20, 9, 16]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[26,  7, 11],
       [20,  9, 16]], dtype=int32)>

In [109]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [110]:
# Tampilkan ukuran dari matrix X

tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [111]:
# Tampilkan seluruh elemen dari kolom pertama

X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([20,  9, 16], dtype=int32)>