# Penyelesaian Soal Transpose of **vector**

In [ ]:
import numpy as np

In [ ]:
x = np.array([[25], [2],  [-3], [-23]])
x

array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [ ]:
# Tampilkan ukuran dari vector x_t
x_t.shape

(1, 4)

In [ ]:
# Lakukan transpose pada vector x
x_t = x.T
x_t


array([[ 25,   2,  -3, -23]])

In [ ]:
# transposed back to original row vector
x_t.T

array([[ 25],
       [  2],
       [ -3],
       [-23]])

In [ ]:
x_t.T.shape

(4, 1)

### Vectors in PyTorch and TensorFlow

In [ ]:
import torch
import tensorflow as tf


In [ ]:
x_pt = torch.tensor([[25], [2],  [-3], [-23]])
x_pt

tensor([[ 25],
        [  2],
        [ -3],
        [-23]])

In [ ]:
x_tf = tf.Variable([[26],[7], [11]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[26],
       [ 7],
       [11]], dtype=int32)>