### Orthogonal Vectors

**1**

In [37]:
import numpy as np

In [38]:
# Membuat vector i
i = np.array([1, 0])
i

array([1, 0])

In [39]:
# Membuat vector j
j = np.array([0, 1])
j

array([0, 1])

In [40]:
# Menghitung dot product untuk membuktikan orthogonality

np.dot(i, j) # detail on the dot operation coming up...

np.int64(0)

**2**

In [41]:
# membuat vector v
v = np.array([1, 2])
v

array([1, 2])

In [42]:
# membuat  vector w
w = np.array([2, -1])
w

array([ 2, -1])

In [43]:
# menghitung dot product membuktikan ortho
np.dot(v, w) # detail on the dot operation coming up...

np.int64(0)